import Head from 'next/head';

import { useRouter } from 'next/router';

import { Box } from '@chakra-ui/react';

import { useSupabase } from '../../hooks/useSupabase.js';

import Header from '../../components/Header';
import Nav from '../../components/Nav';
import EditEpisodes from '../../components/EditEpisodes';
import Published from '../../components/Published';

import { sessionAtom } from '../../atoms';
import { useAtom } from 'jotai';
import AddLinks from '../../components/AddLinks.js';

export default function Home() {
  const [session, setSession] = useAtom(sessionAtom);

  const supabase = useSupabase();

  const router = useRouter();
  const { id: pid } = router.query;

  return (
    <Box>
      <Head>
        <title>Edit Episode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav hProp="auto" />
      <Box
        w="100%"
        h="1vh"
        bgGradient="linear(to-r, #ff96bc,
      #ffc477 ,
      #fbe84a ,
      #c1f3a1 ,
      #96fce4 )"
      />
      <Header text="Edit Episode" />

      <Box
        as="main"
        h="100%"
        w="100vw"
        d="flex"
        justifyContent="space-around"
        mb="50px"
      >
        <Box w="50%" d="flex" justifyContent="center">
          <EditEpisodes pid={pid} />
        </Box>
        <Box w="50%" d="flex" flexDir="column" alignItems="center">
          <Published pid={pid} />
          <AddLinks pid={pid} />
        </Box>
      </Box>
    </Box>
  );
}
