import Head from 'next/head';

import { useRouter } from 'next/router';

import { Box } from '@chakra-ui/react';

import { useEffect } from 'react';

import { useSupabase } from '../../hooks/useSupabase.js';

import Header from '../../components/Header';
import Nav from '../../components/Nav';

import { sessionAtom } from '../../atoms';
import { useAtom } from 'jotai';

export default function Home() {
  const [session, setSession] = useAtom(sessionAtom);

  const supabase = useSupabase();

  const router = useRouter();
  const { id: pid } = router.query;

  console.log(pid);
  // useEffect(() => {
  //   setSession(supabase.auth.session());

  //   supabase.auth.onAuthStateChange((_event, session) => {
  //     setSession(supabase.auth.session());
  //   });
  // }, []);

  return (
    <Box>
      <Head>
        <title>Edit Episode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav hProp="auto" />
      <Box
        w="100%"
        h="1vh"
        bgGradient="linear(to-r, #ff96bc,
      #ffc477 ,
      #fbe84a ,
      #c1f3a1 ,
      #96fce4 )"
      />
      <Header text="Edit Episode" />

      <Box as="main" h="100%" w="100vw" d="flex" justifyContent="center">
        {pid}
      </Box>
    </Box>
  );
}
