import Head from 'next/head';

import { Box } from '@chakra-ui/react';

import { useEffect } from 'react';

import { useSupabase } from '../hooks/useSupabase.js';

import Header from '../components/Header';
import Nav from '../components/Nav';
import AddEpisode from '../components/AddEpisode';

import { sessionAtom } from '../atoms';
import { useAtom } from 'jotai';

export default function Home() {
  const [session, setSession] = useAtom(sessionAtom);

  const supabase = useSupabase();

  useEffect(() => {
    setSession(supabase.auth.session());

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(supabase.auth.session());
    });
  }, []);

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav hProp="auto" />
      <Box
        w="100%"
        h="1vh"
        bgGradient="linear(to-r, #ff96bc,
      #ffc477 ,
      #fbe84a ,
      #c1f3a1 ,
      #96fce4 )"
      />
      <Header text="Add Episode" />

      <Box as="main" h="100%" w="100vw" d="flex" justifyContent="center">
        <AddEpisode />
      </Box>
    </Box>
  );
}
