import Head from 'next/head';

import { Box } from '@chakra-ui/react';

import { useEffect } from 'react';

import { useSupabase } from '../hooks/useSupabase.js';

import Header from '../components/Header';
import AddEpisode from '../components/AddEpisode';

import { sessionAtom } from '../atoms';
import { useAtom } from 'jotai';

export default function Home() {
  const [session, setSession] = useAtom(sessionAtom);

  const supabase = useSupabase();

  useEffect(() => {
    setSession(supabase.auth.session());

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(supabase.auth.session());
    });
  }, []);

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header text="Add Episode" />

      <Box as="main" h="90vh" w="100vw" d="flex" justifyContent="center">
        <AddEpisode />
      </Box>
    </Box>
  );
}
