import Head from "next/head";

import styles from "../styles/Home.module.css";

const axios = require("axios");
import { DateTime } from "luxon";

export default function Home({}) {
  let dateTime = DateTime.local();
  let dateTimeFormatted = dateTime.toLocaleString({
    weekday: "short",
    month: "long",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  var portlandTime = dateTime.setZone("America/Los_Angeles").toLocaleString({
    weekday: "short",
    month: "long",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  /**  */
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div> New Zealand: {JSON.stringify(dateTimeFormatted)}</div>
        <div> Portland {JSON.stringify(portlandTime)}</div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const avatarData = await axios.get(
    "https://last-airbender-api.herokuapp.com/api/v1/characters/random"
  );

  const avatarCh = await avatarData.data;
  console.log(avatarCh);
  return {
    props: {
      avatarCh,
    },
  };
}
