import data from "../data.json";

import Head from "next/head";

import styles from "../styles/Home.module.css";

const axios = require("axios");

import Header from "../components/Header";
import Container from "../components/Container";

export default function Home({ data }) {
  // Making an object date and timefrom Supabase Date data

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Container data={data} />
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      data,
    },
  };
}
