import data from "../data.json";

import Head from "next/head";

import styles from "../styles/Home.module.css";

const axios = require("axios");
import { DateTime } from "luxon";

export default function Home({ data }) {
  // Making an object date and timefrom Supabase Date data
  let objFromData = DateTime.fromISO(`${data[0].us_date}T${data[0].us_time}`);

  //Creating the base date object in PT, so the initial date can be entered into the db as PT
  let ptObj = DateTime.fromObject(
    {
      day: objFromData.c.day,
      hour: objFromData.c.hour,
      minute: objFromData.c.minute,
      month: objFromData.c.month,
      year: objFromData.c.year,
    },
    { zone: "America/Los_Angeles" }
  );

  //Formatting the Pt object to a friendly user format
  let ptObjStr = ptObj.toFormat("ff");

  // Converting the PT object to a a NZ object
  let nzObj = ptObj.setZone("Pacific/Auckland");

  //Formatting the NZ object to a friendly user format
  let nzObjStr = nzObj.toFormat("ff");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>Date from data: {ptObjStr}</div>
        <div>NZ date from data: {nzObjStr}</div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      data,
    },
  };
}
