import Head from 'next/head';

import { Box, FormControl, FormLabel, Input, Button } from '@chakra-ui/react';

import { useEffect, useRef } from 'react';
import { useRouter } from 'next/router';

import { useSupabase } from '../hooks/useSupabase.js';

import Header from '../components/Header';

import { sessionAtom } from '../atoms';
import { useAtom } from 'jotai';

export default function Home() {
  const [session, setSession] = useAtom(sessionAtom);
  const passwordRef = useRef('');

  const router = useRouter();

  const supabase = useSupabase();

  useEffect(() => {
    setSession(supabase.auth.session());

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(supabase.auth.session());
    });
  }, []);

  const handleReset = async () => {
    const { user, error } = await supabase.auth.update({
      password: passwordRef.current.value,
    });

    if (error) {
      console.log(error);
    }

    router.push('/');
  };

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header text="Reset Password" />

      <Box
        as="main"
        h="90vh"
        w="100vw"
        d="flex"
        justifyContent="center"
        alignItems="center"
      >
        <FormControl
          h="40%"
          w="40%"
          d="flex"
          justifyContent="center"
          flexDir="column"
        >
          <FormLabel
            id="password"
            htmlFor="password"
            d="flex"
            justifyContent="center"
          >
            Password
          </FormLabel>
          <Input ref={passwordRef} id="password" type="password" />
          <Button onClick={handleReset}>Submit</Button>
        </FormControl>
      </Box>
    </Box>
  );
}
