import Head from 'next/head';

import { Box } from '@chakra-ui/react';

import { useEffect, useState } from 'react';

import Header from '../components/Header';
import Nav from '../components/Nav';

import Container from '../components/kanban/Container';

import { useSupabase } from '../hooks/useSupabase.js';

import { DateTime } from 'luxon';

export default function Home() {
  const [eps, setEps] = useState([]);
  let julyEps = [];

  const supabase = useSupabase();

  useEffect(async () => {
    const { data, error } = await supabase
      .from('episodes')
      .select()
      .order('default_date', { ascending: true });

    setEps(data);
  }, []);

  eps.forEach((ep, i) => {
    let dt = DateTime.fromISO(`${ep.default_date}T${ep.default_time}`);
    let zone = 'America/Los_Angeles';
    let zonedDt = DateTime.fromObject(
      {
        day: dt.c.day,
        hour: dt.c.hour,
        minute: dt.c.minute,
        month: dt.c.month,
        year: dt.c.year,
      },
      { zone }
    );
    let dateISO = zonedDt.toLocaleString({
      month: 'long',
    });

    if (dateISO.toLowerCase() === 'july') {
      julyEps.push(ep);
    }
  });

  return (
    <Box h="100vh" w="100vw">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav hProp="auto" />
      <Box
        w="100%"
        h="1vh"
        bgGradient="linear(to-r, #ff96bc,
      #ffc477 ,
      #fbe84a ,
      #c1f3a1 ,
      #96fce4 )"
      />
      <Header text="Upcoming Episodes" hProp="10vh" />

      <Box
        as="main"
        h="100%"
        w="100vw"
        d="flex"
        justifyContent="center"
        alignItems="center"
        color="blue"
      >
        <Container eps={julyEps}></Container>
      </Box>
    </Box>
  );
}
